package com.axone_io.ignition.git.managers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * GitHub REST API client for creating hotfix PRs.
 * Uses Java's built-in HttpClient — no external dependencies.
 */
public class GitHubApiManager {
    private static final Logger logger = LoggerFactory.getLogger(GitHubApiManager.class);
    private static final String GITHUB_API_BASE = "https://api.github.com";

    private static final Pattern HTTPS_PATTERN = Pattern.compile(
        "https?://github\\.com/([^/]+)/([^/.]+?)(?:\\.git)?/?$"
    );
    private static final Pattern SSH_PATTERN = Pattern.compile(
        "git@github\\.com:([^/]+)/([^/.]+?)(?:\\.git)?$"
    );

    /**
     * Parse owner and repo name from a GitHub URL.
     * Supports HTTPS and SSH formats.
     * Returns [owner, repo] or null if not a valid GitHub URL.
     */
    public static String[] parseOwnerRepo(String repoUri) {
        if (repoUri == null) return null;

        Matcher httpsMatcher = HTTPS_PATTERN.matcher(repoUri);
        if (httpsMatcher.matches()) {
            return new String[]{httpsMatcher.group(1), httpsMatcher.group(2)};
        }

        Matcher sshMatcher = SSH_PATTERN.matcher(repoUri);
        if (sshMatcher.matches()) {
            return new String[]{sshMatcher.group(1), sshMatcher.group(2)};
        }

        return null;
    }

    /**
     * Sanitize a hotfix description into a valid git branch name segment.
     * Lowercase, spaces to hyphens, strip special chars, collapse consecutive hyphens.
     */
    public static String sanitizeBranchName(String description) {
        return description.toLowerCase()
            .replaceAll("[^a-z0-9\\s-]", "")
            .trim()
            .replaceAll("\\s+", "-")
            .replaceAll("-{2,}", "-")
            .replaceAll("-$", "");
    }

    /**
     * Build the PR body markdown for a hotfix PR.
     */
    public static String buildPrBody(String userName, String gatewayName, String projectName,
                                     String hotfixBranch, String commitHash, String commitMessage,
                                     String[] changes) {
        String timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now());

        StringBuilder body = new StringBuilder();
        body.append("## Production Hotfix \u2014 Already Live\n\n");
        body.append("This fix was applied directly to the production gateway and is **already running**.\n\n");
        body.append("| | |\n|---|---|\n");
        body.append("| **Applied by** | ").append(userName).append(" |\n");
        body.append("| **Applied at** | ").append(timestamp).append(" |\n");
        body.append("| **Gateway** | ").append(gatewayName).append(" |\n");
        body.append("| **Project** | ").append(projectName).append(" |\n");
        body.append("| **Branch** | ").append(hotfixBranch).append(" |\n");
        body.append("| **Commit** | ").append(commitHash).append(" |\n\n");

        if (changes != null && changes.length > 0) {
            body.append("### Changes\n");
            for (String change : changes) {
                body.append("- ").append(change).append("\n");
            }
            body.append("\n");
        }

        body.append("### Commit Message\n");
        body.append(commitMessage).append("\n\n");
        body.append("---\n");
        body.append("Auto-generated by Ignition Git Module (Production Hotfix Workflow)\n");

        return body.toString();
    }

    /**
     * Create a pull request on GitHub.
     * Returns the PR URL on success, null on failure.
     */
    public static CreatePrResult createPullRequest(String repoUri, String token,
                                                   String headBranch, String baseBranch,
                                                   String title, String body) {
        String[] ownerRepo = parseOwnerRepo(repoUri);
        if (ownerRepo == null) {
            logger.error("[Production Hotfix] Cannot parse GitHub owner/repo from URI: {}", repoUri);
            return new CreatePrResult(null, 0, "Cannot parse GitHub owner/repo from URI: " + repoUri);
        }

        String owner = ownerRepo[0];
        String repo = ownerRepo[1];

        try {
            // Escape JSON strings
            String jsonBody = String.format(
                "{\"title\":\"%s\",\"body\":\"%s\",\"head\":\"%s\",\"base\":\"%s\"}",
                escapeJson(title),
                escapeJson(body),
                escapeJson(headBranch),
                escapeJson(baseBranch)
            );

            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(GITHUB_API_BASE + "/repos/" + owner + "/" + repo + "/pulls"))
                .header("Authorization", "Bearer " + token)
                .header("Accept", "application/vnd.github+json")
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(jsonBody))
                .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() == 201) {
                // Parse PR URL and number from response
                String responseBody = response.body();
                String prUrl = extractJsonString(responseBody, "html_url");
                int prNumber = extractJsonInt(responseBody, "number");

                logger.info("[Production Hotfix] PR #{} created: {}", prNumber, prUrl);

                // Try to add labels (best-effort — if this fails, the PR still exists)
                addLabels(client, token, owner, repo, prNumber);

                return new CreatePrResult(prUrl, prNumber, null);
            } else {
                String errorMsg = "GitHub API returned " + response.statusCode() + ": " + response.body();
                logger.error("[Production Hotfix] PR creation failed: {}", errorMsg);
                return new CreatePrResult(null, 0, errorMsg);
            }
        } catch (Exception e) {
            logger.error("[Production Hotfix] Error creating PR", e);
            return new CreatePrResult(null, 0, e.getMessage());
        }
    }

    private static void addLabels(HttpClient client, String token, String owner, String repo, int prNumber) {
        try {
            String labelJson = "{\"labels\":[\"hotfix\",\"production\"]}";
            HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(GITHUB_API_BASE + "/repos/" + owner + "/" + repo + "/issues/" + prNumber + "/labels"))
                .header("Authorization", "Bearer " + token)
                .header("Accept", "application/vnd.github+json")
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(labelJson))
                .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            if (response.statusCode() != 200) {
                logger.warn("[Production Hotfix] Could not add labels to PR #{}: {} {}",
                    prNumber, response.statusCode(), response.body());
            }
        } catch (Exception e) {
            logger.warn("[Production Hotfix] Error adding labels to PR #{}: {}", prNumber, e.getMessage());
        }
    }

    /** Simple JSON string extraction — avoids adding a JSON library dependency. */
    static String extractJsonString(String json, String key) {
        String search = "\"" + key + "\":\"";
        int start = json.indexOf(search);
        if (start < 0) return null;
        start += search.length();
        int end = json.indexOf("\"", start);
        if (end < 0) return null;
        return json.substring(start, end);
    }

    /** Simple JSON int extraction. */
    static int extractJsonInt(String json, String key) {
        String search = "\"" + key + "\":";
        int start = json.indexOf(search);
        if (start < 0) return 0;
        start += search.length();
        StringBuilder sb = new StringBuilder();
        for (int i = start; i < json.length(); i++) {
            char c = json.charAt(i);
            if (Character.isDigit(c)) sb.append(c);
            else break;
        }
        return sb.length() > 0 ? Integer.parseInt(sb.toString()) : 0;
    }

    private static String escapeJson(String value) {
        if (value == null) return "";
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t");
    }

    /** Result of a PR creation attempt. */
    public static class CreatePrResult {
        private final String prUrl;
        private final int prNumber;
        private final String error;

        public CreatePrResult(String prUrl, int prNumber, String error) {
            this.prUrl = prUrl;
            this.prNumber = prNumber;
            this.error = error;
        }

        public boolean isSuccess() { return prUrl != null; }
        public String getPrUrl() { return prUrl; }
        public int getPrNumber() { return prNumber; }
        public String getError() { return error; }
    }
}
