---
services:
  gateway:
    image: inductiveautomation/ignition:${IGNITION_VERSION:-8.3.3}
    hostname: gateway
    ports:
      - 9088:8088
      - 9043:8043
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_ADMIN_USERNAME=${GATEWAY_ADMIN_USERNAME:-admin}
      - GATEWAY_ADMIN_PASSWORD=${GATEWAY_ADMIN_PASSWORD:-password}
      - GATEWAY_GIT_USER_SECRET=${GATEWAY_GIT_USER_SECRET}
      - IGNITION_EDITION=standard
    networks:
      - default
    volumes:
      - gateway_data:/usr/local/bin/ignition/data
      - ./modules/Git-unsigned.modl:/usr/local/bin/ignition/user-lib/modules/Git-unsigned.modl
      - ./gw-init/git.yaml:/usr/local/bin/ignition/data/git.yaml
    command: >
      -n Ignition-Git

networks:
  default:

volumes:
  gateway_data:
