---
services:
  gateway:
    build:
      context: gw-build
      dockerfile: Dockerfile
      args:
        IGNITION_VERSION: ${IGNITION_VERSION:-8.3.3}
        SUPPLEMENTAL_MODULES: "git"
        GATEWAY_ADMIN_USERNAME: ${GATEWAY_ADMIN_USERNAME:-admin}
        GIT_USER_TOKEN: ${GATEWAY_GIT_USER_SECRET}
      secrets:
        - gateway-admin-password
        - git-user-token
    hostname: gateway
    ports:
      - 9088:8088
      - 9043:8043
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_ADMIN_USERNAME=${GATEWAY_ADMIN_USERNAME:-admin}
      - GATEWAY_ADMIN_PASSWORD=${GATEWAY_ADMIN_PASSWORD:-password}
      - GATEWAY_GIT_USER_SECRET=${GATEWAY_GIT_USER_SECRET}
      - IGNITION_EDITION=standard
    networks:
      - default
    volumes:
      - gateway_data:/usr/local/bin/ignition/data
      - ./gw-init/git.yaml:/usr/local/bin/ignition/data/git.yaml
    command: >
      -n Ignition-Git

networks:
  default:

secrets:
  gateway-admin-password:
    environment: GATEWAY_ADMIN_PASSWORD
  git-user-token:
    environment: GATEWAY_GIT_USER_SECRET

volumes:
  gateway_data:
